#pragma once

#include "CoreMinimal.h"
#include "ShaderModule/Public/ShaderModule.h"  // DOUBLE CHECK THIS IS RIGHT IN THE TEST SHADER CODE TOO
#include "MeshPassProcessor.h"
#include "RenderGraphBuilder.h"
#include "RenderTargetPool.h"
#include "MeshMaterialShader.h"
#include "ShaderParameterUtils.h"
#include "RHIStaticStates.h"
#include "Shader.h"
#include "RHI.h"
#include "GlobalShader.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterStruct.h"
#include "UniformBuffer.h"
#include "RHICommandList.h"
#include "ShaderCompilerCore.h"
#include "Renderer/Private/ScenePrivate.h"
#include "EngineDefines.h"
#include "RendererInterface.h"
#include "RenderResource.h"
#include "RenderGraphResources.h"
#include "RenderingThread.h"

#include "Runtime/Engine/Classes/Engine/TextureRenderTarget2D.h"