#include "/Engine/Public/Platform.ush"


Buffer<int> mapChunkSize;

// RWStructuredBuffer<float> noiseMap;
RWBuffer<float> noiseMap;


[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MySimpleComputeShader(uint3 DispatchThreadId : SV_DispatchThreadID,
						   uint GroupIndex : SV_GroupIndex )
{

	int rollSize = 1000;
	int vertexCount = mapChunkSize[0] * mapChunkSize[0];

	// [unroll(rollSize)]
	for (int i = 0; i < 1000; i++)
	{
		// noiseMap[i] = i;
	}
	// noiseMap[0] = 0;

}
